/**
 * @file Automatically generated by barrelsby.
 */

import * as clits from "./cli";
import * as commandscopytemplatests from "./commands/copytemplates";
import * as commandsgeneratets from "./commands/generate";
import * as optionsclientts from "./options/client";
import * as optionsfiltersts from "./options/filters";
import * as optionsoutputts from "./options/output";
import * as optionsprojectts from "./options/project";
import * as optionstemplatests from "./options/templates";
export {clits as cli};
export const commands = {
  copytemplates: commandscopytemplatests,
  generate: commandsgeneratets,
};
export const options = {
  client: optionsclientts,
  filters: optionsfiltersts,
  output: optionsoutputts,
  project: optionsprojectts,
  templates: optionstemplatests,
};
