/**
 * @file Automatically generated by barrelsby.
 */

import * as cliclits from "./cli/cli";
import * as clicommandscopytemplatests from "./cli/commands/copytemplates";
import * as clicommandsgeneratets from "./cli/commands/generate";
import * as clioptionsclientts from "./cli/options/client";
import * as clioptionsfiltersts from "./cli/options/filters";
import * as clioptionsoutputts from "./cli/options/output";
import * as clioptionsprojectts from "./cli/options/project";
import * as clioptionstemplatests from "./cli/options/templates";
import * as documentationdefaultprocessorts from "./documentation/defaultprocessor";
import * as documentationdefaulttemplatedatats from "./documentation/defaulttemplatedata";
import * as documentationfiltersts from "./documentation/filters";
import * as documentationgeneratets from "./documentation/generate";
import * as documentationoutputts from "./documentation/output";
import * as documentationprocessorts from "./documentation/processor";
import * as documentationtemplatests from "./documentation/templates";
import * as sdkassociationsts from "./sdk/associations";
import * as sdkattributetypests from "./sdk/attributetypes";
import * as sdkdatatypests from "./sdk/datatypes";
import * as sdkdocumenttypests from "./sdk/documenttypes";
import * as sdkprojectsts from "./sdk/projects";
export const cli = {
	cli: cliclits,
	commands: {
		copytemplates: clicommandscopytemplatests,
		generate: clicommandsgeneratets
	},
	options: {
		client: clioptionsclientts,
		filters: clioptionsfiltersts,
		output: clioptionsoutputts,
		project: clioptionsprojectts,
		templates: clioptionstemplatests
	}
};
export const documentation = {
	defaultprocessor: documentationdefaultprocessorts,
	defaulttemplatedata: documentationdefaulttemplatedatats,
	filters: documentationfiltersts,
	generate: documentationgeneratets,
	output: documentationoutputts,
	processor: documentationprocessorts,
	templates: documentationtemplatests
};
export const sdk = {
	associations: sdkassociationsts,
	attributetypes: sdkattributetypests,
	datatypes: sdkdatatypests,
	documenttypes: sdkdocumenttypests,
	projects: sdkprojectsts
};
